In [ ]:
import pandas as pd

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("netflix_titles.csv")

In [ ]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [3]:
data [['show_id' , 'duration']]

       show_id    duration
0     81145628      90 min
1     80117401      94 min
2     70234439    1 Season
3     80058654    1 Season
4     80125979      99 min
...        ...         ...
6229  80000063  13 Seasons
6230  70286564   4 Seasons
6231  80116008      60 min
6232  70281022   2 Seasons
6233  70153404  10 Seasons

[6234 rows x 2 columns]

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   str
 2   title         6234 non-null   str
 3   director      4265 non-null   str
 4   cast          5664 non-null   str
 5   country       5758 non-null   str
 6   date_added    6223 non-null   str
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   str
 9   duration      6234 non-null   str
 10  listed_in     6234 non-null   str
 11  description   6234 non-null   str
dtypes: int64(2), str(10)
memory usage: 584.6 KB

In [5]:
data ['type'].value_counts()

type
Movie      4265
TV Show    1969
Name: count, dtype: int64

*filtration*

In [6]:
data[data['release_year']==2020]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1315,81034946,TV Show,Maradona in Mexico,NaN,Diego Armando Maradona,"Argentina, United States, Mexico","November 13, 2019",2020,TV-MA,1 Season,"Docuseries, Spanish-Language TV Shows","In this docuseries, soccer great Diego Maradon..."
3180,81214114,Movie,Bulletproof 2,Don Michael Paul,"Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...",United States,"January 9, 2020",2020,TV-MA,97 min,"Action & Adventure, Comedies",A special agent abruptly reunites with a crimi...
3189,81039393,TV Show,Cheer,NaN,NaN,United States,"January 8, 2020",2020,TV-MA,1 Season,"Docuseries, Reality TV, Teen TV Shows",This gripping docuseries follows the ups and d...
3195,80233408,Movie,"Live Twice, Love Once",Maria Ripoll,"Oscar Martínez, Inma Cuesta, Mafalda Carbonell...",Spain,"January 7, 2020",2020,TV-MA,102 min,"Comedies, Dramas, International Movies",When Emilio (Oscar Martínez) is diagnosed with...
3220,80997687,TV Show,Dracula,NaN,"Claes Bang, Dolly Wells, John Heffernan",United Kingdom,"January 4, 2020",2020,TV-14,1 Season,"British TV Shows, International TV Shows, TV D...",The Count Dracula legend transforms with new t...
3221,80237347,TV Show,Go! Go! Cory Carson,NaN,"Alan C. Lim, Paul Killam, Maisie Benson, Kerry...",United States,"January 4, 2020",2020,TV-Y,1 Season,Kids' TV,"Beep, beep – go, go! Buckle up for fun and adv..."
3249,81006825,Movie,All the Freckles in the World,Yibrán Asuad,"Hánssel Casillas, Loreto Peralta, Andrea Sutto...",Mexico,"January 3, 2020",2020,TV-14,90 min,"Comedies, International Movies, Romantic Movies",Thirteen-year-old José Miguel is immune to 199...
3325,81160763,TV Show,"Sex, Explained",NaN,Janelle Monáe,United States,"January 2, 2020",2020,TV-MA,1 Season,"Docuseries, Science & Nature TV",From the biology of attraction to the history ...
3352,81127902,Movie,A Fall from Grace,Tyler Perry,"Crystal Fox, Phylicia Rashad, Cicely Tyson, Br...",NaN,"January 17, 2020",2020,TV-MA,121 min,"Dramas, Thrillers","When gentle, law-abiding Grace confesses to ki..."
3353,80995039,TV Show,Ares,NaN,"Jade Olieberg, Tobias Kersloot, Lisa Smit, Fri...",NaN,"January 17, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Horror","Aiming to become part of Amsterdam's elite, an..."
3354,81062580,TV Show,Nailed It! Germany,NaN,"Angelina Kirsch, Bernd Siefert",NaN,"January 17, 2020",2020,TV-14,1 Season,"International TV Shows, Reality TV",Home cooks try – and inevitably fail – to re-c...
3363,80996973,TV Show,Handsome Siblings,NaN,"Hu Yitian, Chen Zheyuan, Liang Jie, Vicky Lian...",China,"January 16, 2020",2020,TV-14,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...",Clashing martial arts twins face relentless vi...
3379,81062828,TV Show,Killer Inside: The Mind of Aaron Hernandez,NaN,Aaron Hernandez,United States,"January 15, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries","Via interviews with friends, players and insid..."
3426,80221553,TV Show,Kipo and the Age of Wonderbeasts,NaN,"Karen Fukuhara, Sydney Mikayla, Deon Cole, Coy...",United States,"January 14, 2020",2020,TV-Y7-FV,1 Season,"Kids' TV, TV Comedies",Making her way through a world of mutant anima...
3427,81060049,Movie,Leslie Jones: Time Machine,"David Benioff, D.B. Weiss",Leslie Jones,United States,"January 14, 2020",2020,TV-MA,66 min,Stand-Up Comedy,From trying to seduce Prince to battling sleep...
3436,80239306,TV Show,The Healing Powers of Dude,NaN,"Jace Chapman, Larisa Oleynik, Tom Everett Scot...",NaN,"January 13, 2020",2020,TV-G,1 Season,"Kids' TV, TV Comedies, TV Dramas",When an 11-year-old boy with social anxiety di...
3464,80237329,TV Show,AJ and the Queen,NaN,"RuPaul Charles, Izzy G., Michael-Leon Wooley, ...",United States,"January 10, 2020",2020,TV-14,1 Season,"TV Comedies, TV Dramas",While traveling across the country in a run-do...
3466,81183491,TV Show,Jamtara - Sabka Number Ayega,Soumendra Padhi,"Amit Sial, Dibyendu Bhattacharya, Aksha Pardha...",India,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A group of small-town young men run a lucrativ...
3467,81011449,TV Show,Medical Police,NaN,"Erinn Hayes, Rob Huebel, Malin Akerman, Rob Co...",United States,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, TV Action & Adventure, TV Come...",Doctors Owen Maestro and Lola Spratt leave Chi...
3472,81074060,TV Show,Until Dawn,NaN,"Ahmed Sylla, Alban Ivanov, Ornella Fleury, Nat...",France,"January 10, 2020",2020,TV-MA,1 Season,"International TV Shows, Reality TV, TV Comedies",France’s funniest comics carry out ghastly tas...
3518,81088083,Movie,Ghost Stories,"Anurag Kashyap, Dibakar Banerjee, Karan Johar,...","Janhvi Kapoor, Sobhita Dhulipala, Sukant Goel,...",India,"January 1, 2020",2020,TV-MA,145 min,"Horror Movies, International Movies, Thrillers","The directors of Emmy-nominated ""Lust Stories""..."
3541,80117557,TV Show,Messiah,NaN,"Michelle Monaghan, Mehdi Dehbi, John Ortiz, To...",United States,"January 1, 2020",2020,TV-MA,1 Season,"TV Dramas, TV Thrillers",A wary CIA officer investigates a charismatic ...
3546,80197991,TV Show,"Nisman: The Prosecutor, the President, and the...",Justin Webster,NaN,NaN,"January 1, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries details the suspicious death o...
3562,80201590,TV Show,Spinning Out,NaN,"Kaya Scodelario, January Jones, Will Kemp, Wil...",NaN,"January 1, 2020",2020,TV-MA,1 Season,TV Dramas,A figure skating Olympic hopeful struggles to ...
3573,81044551,TV Show,The Circle,NaN,Michelle Buteau,NaN,"January 1, 2020",2020,TV-MA,1 Season,Reality TV,Status and strategy collide in this social exp...

In [15]:
data.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [8]:
data ['country'].nunique()

554

In [4]:
data[data['country'].str.contains('554')]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [5]:
data['country'].isnull().sum()

np.int64(476)

In [6]:
data['country'] = data['country'].fillna('no value')

In [7]:
data[data['country'].str.contains('no value')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
10,80169755,Movie,Joaquín Reyes: Una y no más,José Miguel Contreras,Joaquín Reyes,no value,"September 8, 2017",2017,TV-MA,78 min,Stand-Up Comedy,Comedian and celebrity impersonator Joaquín Re...
12,80182480,Movie,Krish Trish and Baltiboy,NaN,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",no value,"September 8, 2017",2009,TV-Y7,58 min,Children & Family Movies,"A team of minstrels, including a monkey, cat a..."
13,80182483,Movie,Krish Trish and Baltiboy: Battle of Wits,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Baba S...",no value,"September 8, 2017",2013,TV-Y7,62 min,Children & Family Movies,"An artisan is cheated of his payment, a lion o..."
14,80182596,Movie,Krish Trish and Baltiboy: Best Friends Forever,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Deepak...",no value,"September 8, 2017",2016,TV-Y,65 min,Children & Family Movies,"A cat, monkey and donkey team up to narrate fo..."
15,80182482,Movie,Krish Trish and Baltiboy: Comics of India,Tilak Shetty,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",no value,"September 8, 2017",2012,TV-Y7,61 min,Children & Family Movies,"In three comic-strip-style tales, a boy tries ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
6170,80136456,TV Show,Age of Glory,NaN,"Debbie Goh, Aenie Wong, Frederick Lee, Leslie ...",no value,"August 14, 2017",2010,TV-PG,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Amid the thriving nightlife of 1960s Kuala Lum...
6195,80136790,TV Show,Goodnight DJ 1,NaN,"Chan Fong, Z-Chen, Frederick Lee, Melvin Sia, ...",no value,"April 27, 2018",2016,TV-14,2 Seasons,"International TV Shows, TV Dramas, TV Horror",Young radio announcers from varying background...
6199,80244228,TV Show,Beauty and the Bitches,NaN,"Methinee Kingpayome, Son Songpaisarn, Yingying...",no value,"April 23, 2019",2016,TV-14,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Beauty pageant contestants from all over Thail...
6228,80159925,TV Show,Kikoriki,NaN,Igor Dmitriev,no value,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,no value,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...

In [ ]:
data['First_actor'] = data['cast'].str.split(',,').str[1]
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,First_actor
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,Andrew Toth
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,NaN
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",Sumalee Montano
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,Darren Criss
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,Kate Walsh

In [3]:
data = pd.read_csv("netflix_titles.csv")

In [6]:
data.groupby('release_year')['title'].count()

release_year
1925       1
1942       2
1943       3
1944       3
1945       3
        ...
2016     830
2017     959
2018    1063
2019     843
2020      25
Name: title, Length: 72, dtype: int64

In [7]:
data[data['title'].str.contains("love")]
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016-09-09,2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09-08,2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09-08,2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09-08,2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [11]:
data[data['director'].str.contains('Gaspar Noe')]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [5]:
data['release_year'].min()

np.int64(1925)

In [4]:
data['release_year'].max()

np.int64(2020)

In [6]:
data[(data['release_year']==2020)&
     (data['type']=='TV Show')
     ]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1315,81034946,TV Show,Maradona in Mexico,NaN,Diego Armando Maradona,"Argentina, United States, Mexico","November 13, 2019",2020,TV-MA,1 Season,"Docuseries, Spanish-Language TV Shows","In this docuseries, soccer great Diego Maradon..."
3189,81039393,TV Show,Cheer,NaN,NaN,United States,"January 8, 2020",2020,TV-MA,1 Season,"Docuseries, Reality TV, Teen TV Shows",This gripping docuseries follows the ups and d...
3220,80997687,TV Show,Dracula,NaN,"Claes Bang, Dolly Wells, John Heffernan",United Kingdom,"January 4, 2020",2020,TV-14,1 Season,"British TV Shows, International TV Shows, TV D...",The Count Dracula legend transforms with new t...
3221,80237347,TV Show,Go! Go! Cory Carson,NaN,"Alan C. Lim, Paul Killam, Maisie Benson, Kerry...",United States,"January 4, 2020",2020,TV-Y,1 Season,Kids' TV,"Beep, beep – go, go! Buckle up for fun and adv..."
3325,81160763,TV Show,"Sex, Explained",NaN,Janelle Monáe,United States,"January 2, 2020",2020,TV-MA,1 Season,"Docuseries, Science & Nature TV",From the biology of attraction to the history ...
3353,80995039,TV Show,Ares,NaN,"Jade Olieberg, Tobias Kersloot, Lisa Smit, Fri...",NaN,"January 17, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Horror","Aiming to become part of Amsterdam's elite, an..."
3354,81062580,TV Show,Nailed It! Germany,NaN,"Angelina Kirsch, Bernd Siefert",NaN,"January 17, 2020",2020,TV-14,1 Season,"International TV Shows, Reality TV",Home cooks try – and inevitably fail – to re-c...
3363,80996973,TV Show,Handsome Siblings,NaN,"Hu Yitian, Chen Zheyuan, Liang Jie, Vicky Lian...",China,"January 16, 2020",2020,TV-14,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...",Clashing martial arts twins face relentless vi...
3379,81062828,TV Show,Killer Inside: The Mind of Aaron Hernandez,NaN,Aaron Hernandez,United States,"January 15, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries","Via interviews with friends, players and insid..."
3426,80221553,TV Show,Kipo and the Age of Wonderbeasts,NaN,"Karen Fukuhara, Sydney Mikayla, Deon Cole, Coy...",United States,"January 14, 2020",2020,TV-Y7-FV,1 Season,"Kids' TV, TV Comedies",Making her way through a world of mutant anima...
3436,80239306,TV Show,The Healing Powers of Dude,NaN,"Jace Chapman, Larisa Oleynik, Tom Everett Scot...",NaN,"January 13, 2020",2020,TV-G,1 Season,"Kids' TV, TV Comedies, TV Dramas",When an 11-year-old boy with social anxiety di...
3464,80237329,TV Show,AJ and the Queen,NaN,"RuPaul Charles, Izzy G., Michael-Leon Wooley, ...",United States,"January 10, 2020",2020,TV-14,1 Season,"TV Comedies, TV Dramas",While traveling across the country in a run-do...
3466,81183491,TV Show,Jamtara - Sabka Number Ayega,Soumendra Padhi,"Amit Sial, Dibyendu Bhattacharya, Aksha Pardha...",India,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A group of small-town young men run a lucrativ...
3467,81011449,TV Show,Medical Police,NaN,"Erinn Hayes, Rob Huebel, Malin Akerman, Rob Co...",United States,"January 10, 2020",2020,TV-MA,1 Season,"Crime TV Shows, TV Action & Adventure, TV Come...",Doctors Owen Maestro and Lola Spratt leave Chi...
3472,81074060,TV Show,Until Dawn,NaN,"Ahmed Sylla, Alban Ivanov, Ornella Fleury, Nat...",France,"January 10, 2020",2020,TV-MA,1 Season,"International TV Shows, Reality TV, TV Comedies",France’s funniest comics carry out ghastly tas...
3541,80117557,TV Show,Messiah,NaN,"Michelle Monaghan, Mehdi Dehbi, John Ortiz, To...",United States,"January 1, 2020",2020,TV-MA,1 Season,"TV Dramas, TV Thrillers",A wary CIA officer investigates a charismatic ...
3546,80197991,TV Show,"Nisman: The Prosecutor, the President, and the...",Justin Webster,NaN,NaN,"January 1, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries details the suspicious death o...
3562,80201590,TV Show,Spinning Out,NaN,"Kaya Scodelario, January Jones, Will Kemp, Wil...",NaN,"January 1, 2020",2020,TV-MA,1 Season,TV Dramas,A figure skating Olympic hopeful struggles to ...
3573,81044551,TV Show,The Circle,NaN,Michelle Buteau,NaN,"January 1, 2020",2020,TV-MA,1 Season,Reality TV,Status and strategy collide in this social exp...

In [7]:
data[
    (data['country']=='United States')&
    (data['type']=='TV Show')
]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
8,80117902,TV Show,Fire Chasers,NaN,NaN,United States,"September 8, 2017",2017,TV-MA,1 Season,"Docuseries, Science & Nature TV","As California's 2016 fire season rages, brave ..."
54,80113482,TV Show,No Tomorrow,NaN,"Joshua Sasse, Tori Anderson, Jonathan Langdon,...",United States,"September 5, 2017",2016,TV-14,1 Season,"Romantic TV Shows, TV Comedies, TV Dramas",Her straitjacketed life turned topsy-turvy by ...
61,80113641,TV Show,Frequency,NaN,"Peyton List, Riley Smith, Mekhi Phifer, Devin ...",United States,"September 4, 2017",2016,TV-14,1 Season,"Crime TV Shows, TV Dramas, TV Mysteries",A detective seizes a precious opportunity to c...
...,...,...,...,...,...,...,...,...,...,...,...,...
6225,70153412,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6226,70243132,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [8]:
data[data['director'].str.contains('Gaspar Noé')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
19,80057969,Movie,Love,Gaspar Noé,"Karl Glusman, Klara Kristin, Aomi Muyock, Ugo ...","France, Belgium","September 8, 2017",2015,NR,135 min,"Cult Movies, Dramas, Independent Movies",A man in an unsatisfying marriage recalls the ...

In [9]:
data['date_added'] = pd.to_datetime(data['date_added'].str.strip())

AttributeError: Can only use .str accessor with string values, not datetime64

In [3]:
data.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
5,80163890,TV Show,Apaches,NaN,"Alberto Ammann, Eloy Azorín, Verónica Echegui,...",Spain,"September 8, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A young journalist is forced into a life of cr...
6,70304989,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","In a dystopian future, an insurance adjuster f..."
7,80164077,Movie,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,TV-MA,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...
8,80117902,TV Show,Fire Chasers,NaN,NaN,United States,"September 8, 2017",2017,TV-MA,1 Season,"Docuseries, Science & Nature TV","As California's 2016 fire season rages, brave ..."
9,70304990,Movie,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,R,90 min,"Action & Adventure, Thrillers",A struggling couple can't believe their luck w...

In [4]:

data['rating'].value_counts()

rating
TV-MA       2027
TV-14       1698
TV-PG        701
R            508
PG-13        286
NR           218
PG           184
TV-Y7        169
TV-G         149
TV-Y         143
TV-Y7-FV      95
G             37
UR             7
NC-17          2
Name: count, dtype: int64

In [5]:
data.groupby('country')['type'].value_counts()

country                                              type
Argentina                                            Movie      26
                                                     TV Show    12
Argentina, Brazil, France, Poland, Germany, Denmark  Movie       1
Argentina, Chile                                     Movie       1
Argentina, Chile, Peru                               Movie       1
                                                                ..
Uruguay, Spain, Mexico                               Movie       1
Venezuela                                            Movie       1
Venezuela, Colombia                                  Movie       1
Vietnam                                              Movie       4
West Germany                                         Movie       1
Name: count, Length: 636, dtype: int64

In [6]:
data[data['cast'].str.contains("Shah Rukh Khan")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
533,81121023,Movie,My Next Guest with David Letterman and Shah Ru...,Michael Steed,"Shah Rukh Khan, David Letterman",NaN,"October 25, 2019",2019,TV-PG,61 min,International Movies,"""King of Bollywood"" Shah Rukh Khan opens up ab..."
1649,80164778,Movie,Raees,Rahul Dholakia,"Shah Rukh Khan, Mahira Khan, Nawazuddin Siddiq...",India,"May 26, 2017",2017,NR,143 min,"Action & Adventure, Dramas, International Movies",After street smart kid Raees rises to become G...
1686,81005364,Movie,Zero,Aanand Rai,"Shah Rukh Khan, Anushka Sharma, Katrina Kaif, ...",India,"May 21, 2019",2018,TV-14,159 min,"Comedies, Dramas, International Movies",Through his relationships with two wildly diff...
1761,80157133,Movie,Chamatkar,Rajiv Mehra,"Shah Rukh Khan, Naseeruddin Shah, Urmila Maton...",India,"May 15, 2017",1992,TV-14,164 min,"Comedies, International Movies, Sci-Fi & Fantasy",A village schoolteacher and the ghost of a mur...
1764,80157083,Movie,Kabhi Haan Kabhi Naa,Kundan Shah,"Shah Rukh Khan, Suchitra Krishnamoorthi, Deepa...",India,"May 15, 2017",1994,TV-14,151 min,"Comedies, Dramas, International Movies",A dreamer falls for a girl who is in love with...
1767,24081514,Movie,Ram Jaane,Rajiv Mehra,"Shah Rukh Khan, Juhi Chawla, Vivek Mushran, Pa...",India,"May 15, 2017",1995,TV-14,142 min,"Dramas, International Movies, Music & Musicals","Two boyhood pals – one righteous, the other a ..."
1884,80158395,Movie,Chaahat,Mahesh Bhatt,"Naseeruddin Shah, Shah Rukh Khan, Pooja Bhatt,...",India,"May 1, 2017",1996,NR,148 min,"Dramas, International Movies, Romantic Movies",A vulnerable singer is forced to choose betwee...
1890,20764666,Movie,English Babu Desi Mem,Praveen Nischol,"Shah Rukh Khan, Sonali Bendre, Rajeshwari, Sae...",India,"May 1, 2017",1996,TV-14,163 min,"Comedies, Dramas, International Movies","After his brother dies, wealthy Vikram relucta..."
2216,60021758,Movie,Asoka,Santosh Sivan,"Shah Rukh Khan, Kareena Kapoor, Danny Denzongp...",India,"March 15, 2017",2001,R,168 min,"Action & Adventure, Dramas, International Movies",This elaborate Bollywood epic dramatizes one m...
2221,80156935,Movie,One 2 Ka 4,Shashilal K. Nair,"Shah Rukh Khan, Juhi Chawla, Jackie Shroff, Ni...",India,"March 15, 2017",2001,TV-14,160 min,"Action & Adventure, Comedies, Dramas","When his partner is killed, a young cop is for..."
2335,17671454,Movie,Dil Se,Mani Ratnam,"Shah Rukh Khan, Manisha Koirala, Preity Zinta,...",India,"March 1, 2018",1998,TV-14,166 min,"Dramas, International Movies, Romantic Movies",A radio broadcaster's intense attraction to a ...
2363,80059049,Movie,Pardes,Subhash Ghai,"Shah Rukh Khan, Amrish Puri, Mahima Chaudhry, ...",India,"March 1, 2018",1997,TV-14,187 min,"Dramas, International Movies, Romantic Movies","Prompted by loyalty, Arjun plays matchmaker be..."
2370,60035875,Movie,Shakti: The Power,Krishna Vamshi,"Karisma Kapoor, Nana Patekar, Sanjay Kapoor, S...",India,"March 1, 2018",2002,TV-MA,168 min,"Dramas, International Movies, Thrillers",A young mother must break free of the clutches...
2379,70019491,Movie,Swades,Ashutosh Gowariker,"Shah Rukh Khan, Gayatri Joshi, Kishori Balal, ...",India,"March 1, 2018",2004,TV-PG,185 min,"Dramas, International Movies",An Americanized NASA scientist returns to his ...
2394,20717860,Movie,Trimurti,Mukul Anand,"Anil Kapoor, Shah Rukh Khan, Jackie Shroff, Sa...",India,"March 1, 2018",1995,TV-PG,173 min,"Action & Adventure, Dramas, International Movies","After being framed, a policewoman languishing ..."
2742,70057994,Movie,Maya Memsaab,Ketan Mehta,"Deepa Sahi, Farooq Shaikh, Raj Babbar, Shah Ru...","France, United Kingdom, India","June 1, 2017",1993,NR,122 min,"Dramas, International Movies, Music & Musicals","A beautiful, wealthy woman’s insatiable appeti..."
2746,80156937,Movie,Oh Darling Yeh Hai India,Ketan Mehta,"Shah Rukh Khan, Deepa Sahi, Javed Jaffrey, Anu...",India,"June 1, 2017",1995,TV-14,154 min,"Action & Adventure, Comedies, International Mo...",A penniless actor new to Mumbai and a beautifu...
3096,60036112,Movie,Chalte Chalte,Aziz Mirza,"Shah Rukh Khan, Rani Mukerji, Jas Arora, Satis...",India,"July 1, 2018",2003,TV-PG,166 min,"Dramas, International Movies, Romantic Movies",Priya and Raj are polar opposites. Raj is bras...
4067,80091866,Movie,Dilwale,Rohit Shetty,"Shah Rukh Khan, Kajol, Kriti Sanon, Kabir Bedi...",India,"February 1, 2017",2015,TV-14,154 min,"Action & Adventure, Dramas, International Movies","A young couple falls in love, but conflicting ..."
4069,80017528,Movie,Happy New Year,Farah Khan,"Shah Rukh Khan, Deepika Padukone, Abhishek Bac...",India,"February 1, 2017",2014,TV-14,179 min,"Action & Adventure, Comedies, Dramas",A revenge-seeking diamond thief gathers a ragt...
4432,80206847,Movie,Jab Harry Met Sejal,Imtiaz Ali,"Shah Rukh Khan, Anushka Sharma, Aru Krishansh ...",India,"December 2, 2017",2017,TV-14,142 min,"Comedies, International Movies, Romantic Movies",A philandering tour guide in Europe begins to ...
4491,70059026,Movie,Don,Farhan Akhtar,"Shah Rukh Khan, Priyanka Chopra, Arjun Rampal,...",India,"December 15, 2019",2006,TV-MA,169 min,"Action & Adventure, International Movies",A ruthless crime boss and drug lord is nabbed ...
4492,70224999,Movie,Don 2,Farhan Akhtar,"Shah Rukh Khan, Priyanka Chopra, Boman Irani, ...","India, Germany","December 15, 2019",2011,TV-14,148 min,"Action & Adventure, International Movies, Musi...","With Asia under his complete control, criminal..."
4792,70254350,Movie,Chennai Express,Rohit Shetty,"Shah Rukh Khan, Deepika Padukone, Nikitin Dhee...",India,"August 31, 2018",2013,TV-14,135 min,"Action & Adventure, Comedies, International Mo...",What could have been a sad journey turns joyfu...
5308,80158042,Movie,Dear Zindagi,Gauri Shinde,"Alia Bhatt, Shah Rukh Khan, Ira Dubey, Yashasw...",India,"April 25, 2017",2016,TV-PG,149 min,"Comedies, Dramas, International Movies",A young cinematographer with a bright professi...
5513,70115621,Movie,Billu,Priyadarshan,"Irrfan Khan, Shah Rukh Khan, Lara Dutta, Rajpa...",India,"April 1, 2018",2009,TV-PG,132 min,"Dramas, International Movies",An Indian village is abuzz with news that a ma...
5531,70000196,Movie,Main Hoon Na,Farah Khan,"Shah Rukh Khan, Sunil Shetty, Sushmita Sen, Za...",India,"April 1, 2018",2004,TV-14,171 min,"Action & Adventure, Comedies, Dramas",Major Ram Prasad Sharma yearns to see project ...
5534,70083535,Movie,Om Shanti Om,Farah Khan,"Shah Rukh Khan, Deepika Padukone, Shreyas Talp...",India,"April 1, 2018",2007,TV-14,169 min,"Comedies, Dramas, International Movies",Reincarnated 30 years after being killed in a ...
5535,70039405,Movie,Paheli,Amol Palekar,"Shah Rukh Khan, Rani Mukerji, Anupam Kher, Dil...",India,"April 1, 2018",2005,TV-PG,134 min,"Dramas, International Movies, Romantic Movies",Traditional Indian folklore comes alive in thi...
5536,60000722,Movie,Phir Bhi Dil Hai Hindustani,Aziz Mirza,"Shah Rukh Khan, Juhi Chawla, Paresh Rawal, Sat...",India,"April 1, 2018",2000,TV-PG,159 min,"Comedies, Dramas, International Movies","In this Bollywood entertainment, two journalis..."

In [7]:
data['director'].value_counts().head()

director
Raúl Campos, Jan Suter    18
Marcus Raboy              14
Jay Karas                 13
Jay Chapman               12
Martin Scorsese            9
Name: count, dtype: int64

In [15]:
data[(data['type']=='Movie')&
     (data['release_year']>2018)
     ]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
35,81154455,Movie,Article 15,Anubhav Sinha,"Ayushmann Khurrana, Nassar, Manoj Pahwa, Kumud...",India,"September 6, 2019",2019,TV-MA,125 min,"Dramas, International Movies, Thrillers",The grim realities of caste discrimination com...
38,81132437,Movie,Kill Me If You Dare,Şenol Sönmez,"Murat Boz, Seda Bakan, Açelya Topaloğlu, Özgür...",NaN,"September 6, 2019",2019,TV-14,100 min,"Comedies, International Movies, Romantic Movies","Bogged down with money problems, a couple grow..."
44,81176188,Movie,American Factory: A Conversation with the Obamas,NaN,"President Barack Obama, Michelle Obama, Julia ...",NaN,"September 5, 2019",2019,TV-G,10 min,Documentaries,Barack and Michelle Obama talk with directors ...
57,81078908,Movie,The World We Make,Brian Baugh,"Caleb Castille, Rose Reid, Kevin Sizemore, Gre...",United States,"September 4, 2019",2019,PG,108 min,"Dramas, Romantic Movies",A teenage equestrian and a local football play...
...,...,...,...,...,...,...,...,...,...,...,...,...
5451,81041272,Movie,Francesco De Carlo: Cose di Questo Mondo,NaN,Francesco De Carlo,Italy,"April 12, 2019",2019,TV-MA,61 min,Stand-Up Comedy,"Taking the stage in Milan, Francesco De Carlo ..."
5455,81019888,Movie,The Perfect Date,Chris Nelson,"Noah Centineo, Laura Marano, Camila Mendes, Od...",United States,"April 12, 2019",2019,TV-14,91 min,"Comedies, Romantic Movies","To earn money for college, a high schooler lau..."
5463,81026007,Movie,Liss Pereira: Reteniendo líquidos,Fernando Ayllón,Liss Pereira,Brazil,"April 10, 2019",2019,TV-14,59 min,Stand-Up Comedy,A pregnant Liss Pereira shares hilariously unc...
5464,81021447,Movie,The Silence,John R. Leonetti,"Stanley Tucci, Kiernan Shipka, Miranda Otto, K...",Germany,"April 10, 2019",2019,TV-14,91 min,"Horror Movies, Thrillers",With the world under attack by deadly creature...
5469,81086434,Movie,706,Shravan Kumar,"Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...",India,"April 1, 2019",2019,TV-14,118 min,"Horror Movies, International Movies","When a doctor goes missing, his psychiatrist w..."

In [9]:
data ['type'].value_counts()

type
Movie      4265
TV Show    1969
Name: count, dtype: int64

In [10]:
data['release_year'].max()

np.int64(2020)

In [16]:
data[data['type']=='Movie']['release_year'].max()

np.int64(2020)

In [17]:
data['release_year'].unique()

array([2019, 2016, 2013, 2017, 2014, 2015, 2009, 2012, 2010, 2018, 2011,
       2004, 2000, 1983, 1982, 2006, 2005, 2002, 1997, 2008, 2007, 2003,
       1981, 1991, 1994, 1988, 1976, 1973, 1974, 1989, 1986, 1984, 1978,
       1998, 1972, 1979, 1960, 1959, 2001, 1995, 1992, 1990, 1975, 1985,
       1980, 1970, 1996, 1967, 1999, 1987, 1968, 1993, 2020, 1958, 1965,
       1956, 1962, 1955, 1977, 1945, 1946, 1942, 1944, 1947, 1943, 1969,
       1954, 1966, 1971, 1964, 1925, 1963])

In [10]:
data.describe()

            show_id                  date_added  release_year
count  6.234000e+03                        6223    6234.00000
mean   7.670368e+07  2018-07-01 15:36:42.346135    2013.35932
min    2.477470e+05         2008-01-01 00:00:00    1925.00000
25%    8.003580e+07         2017-10-01 00:00:00    2013.00000
50%    8.016337e+07         2018-09-30 00:00:00    2016.00000
75%    8.024489e+07         2019-06-08 00:00:00    2018.00000
max    8.123573e+07         2020-01-18 00:00:00    2020.00000
std    1.094296e+07                         NaN       8.81162